### ISSUE TITLE
Add an extensible Gepetto menu/toolbar

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto#338]

**Comment by borismarin** [comment]
In light of opensourcebrain/redmine#146, here is an initial proposal
- The menu layout is hardcoded into the widget itself (controversial?)
- menu items will be defined in a configuration file, which will look like this:
```
myMenu: 
   buttonOne:
      label: "I am a label"
      icon:  "https://the.icon.url/icon1.svg"
      action: ["G.addWidget(1).setMessage("Hello from button 1"), "G.addWidget(3).setData(aModelTree)"] 
```
   this will, evidently, create a button with the specified icon, which when clicked will execute each one of the entries in _action_ (javascript commands) sequentially.
